### ISSUE TITLE
Client displaying old notifications on receipt of a new one

### ISSUE THREAD

**Issue by michaelbina** [ileitch/rapns#101]
I'm seeing a problem right now where certain clients seem to be in a state where when they receive a new notification, one or two old notifications that they had previously received show up with it as well at the same time.  These old notifications are not showing up in the notifications table as being sent again.  I'm not entirely sure if this is a problem with the library itself or if these messages or somehow being cached on the phone and only displayed again, but wanted to see if anyone here has any insight into this problem.

Any help would be greatly appreciated.  Thanks!

**Comment by alfonsogarza** [comment]
I had that same problem and the nature of the issue lied within the phone application's code - I wasn't clearing them correctly. 

I am not sure if your are in the same situation or not, but I would double check your code on the phone application, in particular regarding how you clear those notifications.

Hope that helps!

**Comment by ileitch** [comment]
I've not seen this before. Did you resolve it? Also are you running more than one rapns?

**Comment by alvises** [comment]
At first, thanks for your great work!

I have the same problem. I have only one instance of rapns running and what sometime happens is that some iphones when are receiving a notification, seems they are receiving 2-3 notifications at the same time, but if they go to see the received time in the notification center these are old (and already notified) notifications... don't really know what to do, if it's a problem of ios, rapns or apple servers..

Cheers,
Alvise

**Comment by ileitch** [comment]
Do you see any indication in the rapns log that the notification has been delivered multiple times?

**Comment by alvises** [comment]
Hi!
Probably I found what the problem is. I'm still using the tag 2.0.5. The people receiving the notifications told me that every notification all the old notifications where displayed again!
What I have tried to do is to clear all the delivered notifications every 5 seconds with this rails code

``` ruby
Rapns::Notification.where(:delivered => true).delete_all
```

Do you know what the problem is in the rapns code?
does the new tag > 3.x solving this?

Thanks!

**Comment by michaelbina** [comment]
@alvises Does this deletion really solve the problem? I don't see any indication that the server is delivering the messages again for any reason.  It is good to have those entries int he database for historical purposes.  Would love to know if you're sure that this solves the problem for you.

**Comment by michaelbina** [comment]
@garzaa - Can you give a little bit more information about what you mean by "clearing" the notifications?  We are still seeing this problem and it is becoming evident that it does not lie in the server code, but in the client, but our iOS devs don't know where the notification could be stored.

**Comment by koloritcm** [comment]
I've seeing this as well, only for my rapns app which should mean the problem is within rapns? I'm using rapns 3.3.0. One notification gets stuck and reappears when newer messages arrive.

@ileitch any news what can cause this? its pretty serious if it happens frequently to users.

**Comment by ileitch** [comment]
What do you mean by 'stuck'? Is an error raised, do you see anything in the logs to indicate the notification was sent twice?

**Comment by ileitch** [comment]
@gunnarblom does the time in notification center indicate the older notifications as being redelivered at the same time as the new one? I'm puzzled how this may be an issue with rapns, especially as you say the old notification only reappears in conjunction of a new notification.

**Comment by koloritcm** [comment]
@ileitch the time in the notification is the old time, it can say "3 days" and show up on the lock screen even if I read the notification three days ago. I haven't dug into this, but the only time I've ever ran inte this problem is with my own app that use rapns.

**Comment by ileitch** [comment]
@gunnarblom I am 99% certain then that the issue is not with Rapns. Rapns does not add any timestamps to notifications (the protocol does not support it). Either the APNs is at fault or your phone.

What version of iOS do you use? Is it jailbroken?

**Comment by koloritcm** [comment]
@ileitch ok, you might be right. I use iOS 6.1, not jailbroken. There are other people in this thread seeing the same thing, I wonder if they have seen it with other tools other than rapns? In that case I guess we can rule out rapns.

**Comment by michaelbina** [comment]
@gunnarblom - have you managed to resolve this issue?   We are still seeing it with our app and I'm looking for a fix because we have lots of users complaining.  I thought that maybe it is that I'm still on a 2.x version of rapns, but it looks like you are on 3.x and are still experiencing it.

We have found this thread on the google forums, as it seems the Gmail app has this issue as well:

http://productforums.google.com/forum/#!topic/gmail/x-AIvOGGR68%5B226-250-false%5D

I'm not entirely sure the solution is what we're looking for as I don't really see duplicates in the rapns_notifications table sent to the same device, but may give it a try anyway to see if it helps.  Wanted to see if we could get any more information from anyone on this thread that was experiencing the same issue.  Any help is appreciated.  Thanks!

**Comment by ileitch** [comment]
Please try 3.4.1, it greatly simplifies some internal concurrency logic.
