### ISSUE TITLE
Freeze server when try to run like a demon

### ISSUE THREAD

**Issue by maceto** [ileitch/rapns#102]
Hello,

I'm trying to run rapns like a demon but the server is freeze after a few seconds, the sentence :

bundle exec rapns production

But if I run the demon with -f the process run perfect, sending the notifications 

bunlde exec rapns production -f

What could be the difference ? Memory usage ? Any idea

I'm using ruby 1.9.3p194, rails 3.2.11, rapns 3.1.0 and rbenv, on Debian

**Comment by ileitch** [comment]
Can you signal the process with USR2 and look for some debug output in the log?

**Comment by maceto** [comment]
Now works, I restarted the server and did a new deploy, and now run like a demon, maybe was a problem on gem installation.

Sorry for create a new issue, and thank you for the answer !
