### ISSUE TITLE
Incompability with postgres_ext

### ISSUE THREAD

**Issue by koloritcm** [ileitch/rapns#104]
I get an error when using rapns together with postgres_ext (https://github.com/dockyard/postgres_ext).

This is the error when executing Rapns.push in Rails console:

[2013-02-18 18:44:01] [ERROR] NoMethodError, undefined method `abstract_class?' for Object:Class
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/model_schema.rb:148:in`reset_table_name'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/model_schema.rb:104:in `table_name'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/model_schema.rb:228:in`columns'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/postgres_ext-0.2.2/lib/postgres_ext/active_record/relation/predicate_builder.rb:32:in `block in build_from_hash'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/postgres_ext-0.2.2/lib/postgres_ext/active_record/relation/predicate_builder.rb:6:in`each'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/postgres_ext-0.2.2/lib/postgres_ext/active_record/relation/predicate_builder.rb:6:in `map'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/postgres_ext-0.2.2/lib/postgres_ext/active_record/relation/predicate_builder.rb:6:in`build_from_hash'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/relation/query_methods.rb:327:in `build_where'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/relation/query_methods.rb:136:in`where'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/postgres_ext-0.2.2/lib/postgres_ext/active_record/relation/query_methods.rb:78:in `where_with_chaining'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/querying.rb:9:in`where'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/rapns-3.1.0/lib/rapns/notification.rb:25:in `block in <class:Notification>'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/scoping/named.rb:180:in`call'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/scoping/named.rb:180:in `block (2 levels) in scope'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/scoping/default.rb:41:in`block in unscoped'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/relation.rb:241:in `block in scoping'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/scoping.rb:98:in`with_scope'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/relation.rb:241:in `scoping'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/scoping/default.rb:41:in`unscoped'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/scoping/named.rb:180:in `block in scope'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/relation/delegation.rb:14:in`block in for_apps'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/relation.rb:241:in `block in scoping'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/scoping.rb:98:in`with_scope'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/relation.rb:241:in `scoping'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/relation/delegation.rb:14:in`for_apps'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/rapns-3.1.0/lib/rapns/daemon/feeder.rb:44:in `block in enqueue_notifications'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/rapns-3.1.0/lib/rapns/daemon/database_reconnectable.rb:16:in`block in with_database_reconnect_and_retry'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/rapns-3.1.0/lib/rapns/daemon/database_reconnectable.rb:15:in`with_database_reconnect_and_retry'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/rapns-3.1.0/lib/rapns/daemon/feeder.rb:41:in `enqueue_notifications'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/rapns-3.1.0/lib/rapns/daemon/feeder.rb:14:in`start'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/rapns-3.1.0/lib/rapns/daemon.rb:52:in `start'
/Users/xxx/.rvm/gems/ruby-1.9.3-p374/gems/rapns-3.1.0/lib/rapns/push.rb:9:in`push'

When removing postgres_ext it works fine.

Any idea what can cause this?

**Comment by koloritcm** [comment]
I isolated the problem and it can be reproduced by calling `Rapns::Notification.for_apps([])`. Might be a problem with postgres_ext and scopes with argument.

I added this patch rapns as a temporary work around where I removed the for_apps filter. Is that a good way or how would you suggest patching to skip the call to for_apps? I only have one app. And because I always call rapns with Rapns.push, I guess all apps are always idle when calling this function?

ADDED TO INITIALIZER:

``` ruby
require 'rapns'
Rapns.require_for_daemon

module Rapns
  module Daemon
    class Feeder
      def self.enqueue_notifications
        begin
          with_database_reconnect_and_retry do
            batch_size = Rapns.config.batch_size
            #idle = Rapns::Daemon::AppRunner.idle.map(&:app)
            relation = Rapns::Notification.ready_for_delivery#.for_apps(idle)
            relation = relation.limit(batch_size) unless Rapns.config.push
            relation.each do |notification|
              Rapns::Daemon::AppRunner.enqueue(notification)
              reflect(:notification_enqueued, notification)
            end
          end
        rescue StandardError => e
          Rapns::Daemon.logger.error(e)
          reflect(:error, e)
        end
      end
    end
  end
end
```

**Comment by koloritcm** [comment]
Just solved it with the patch below. I changed from hash condition to string condition. Same thing but works with postgres_ext for some reason.

``` ruby
Rapns.require_for_daemon

module Rapns
  class Notification < ActiveRecord::Base
    scope :for_apps, lambda { |apps|
      where("app_id IN (?)", apps.map(&:id))
    }
  end
end
```

**Comment by ileitch** [comment]
Reported a issue with postgres_ext: https://github.com/dockyard/postgres_ext/issues/72

**Comment by koloritcm** [comment]
I reported an issue on this as well: https://github.com/dockyard/postgres_ext/issues/68

Seems that someone else ran into the issue as well without rapns, but can't find out the reason and it can't be reproduced by the postgres_ext guy.

If you change to string condition the problem disappears, and I guess there is no down side for this gem with changing it?

**Comment by koloritcm** [comment]
@ileitch Consider changing to string condition to close this issue, there is no downside and it works perfect with postgres_ext.

**Comment by koloritcm** [comment]
@ileitch Seems more people have the same problem, you should change the condition to avoid the problem: https://github.com/jmarkoff/rapns-postgres-ext-patch

**Comment by ileitch** [comment]
@gunnarblom please send a pull request, I'm very busy with work at the moment.
