### ISSUE TITLE
Rapns.push doesn't work twice in a row

### ISSUE THREAD

**Issue by koloritcm** [ileitch/rapns#106]
When calling Rapns.push in a Rails console, it works the first time and notifications are sent. If I add a notification and call Rapns.push again, it returns right away without sending the newly added notification. The second time the logs are empty, no connection established to gateway or feedback service.

Same applies to my production approach where notifications are sent in a Rails controller. Rapns.push only works the first call during the web servers lifetime.

FIRST TIME - WORKS
irb(main):001:0> Rapns.push
   (0.4ms)  SELECT COUNT(_) FROM "rapns_apps" 
  Rapns::App Load (0.4ms)  SELECT "rapns_apps"._ FROM "rapns_apps" 
  Rapns::Notification Load (0.8ms)  SELECT "rapns_notifications".\* FROM "rapns_notifications" WHERE (delivered = 'f' AND failed = 'f' AND (deliver_after IS NULL OR deliver_after < '2013-02-19 01:45:25.102513'))
   (0.3ms)  BEGIN
   (31.1ms)  UPDATE "rapns_notifications" SET "delivered" = 't', ...
   (0.4ms)  COMMIT
=> nil

ADD A NOTIFICATION
irb(main):002:0> Rapns::Apns::Notification.create(app: Rapns::Apns::App.first, device_token: "xxx", alert: "My message")
  Rapns::Apns::App Load (1.0ms)  SELECT "rapns_apps".\* FROM "rapns_apps" WHERE "rapns_apps"."type" IN ('Rapns::Apns::App') LIMIT 1
   (0.3ms)  BEGIN
  SQL (3.4ms)  INSERT INTO ...
   (0.4ms)  COMMIT

SECOND TIME - RETURNS DIRECTLY, NOTIFICATION NOT SENT
irb(main):003:0> Rapns.push
   (0.4ms)  SELECT COUNT(_) FROM "rapns_apps" 
  Rapns::App Load (0.4ms)  SELECT "rapns_apps"._ FROM "rapns_apps" 
  Rapns::Notification Load (0.5ms)  SELECT "rapns_notifications".\* FROM "rapns_notifications" WHERE (delivered = 'f' AND failed = 'f' AND (deliver_after IS NULL OR deliver_after < '2013-02-19 01:46:38.670297'))
=> nil

**Comment by koloritcm** [comment]
It appears rapns doesn't support restart of a delivery handler or apns feedback receiver that has been stopped. I did some minor patches to make it work (see comments):

``` ruby
module Rapns
  module Daemon
    class AppRunner

      def stop
        handlers.map(&:stop)
        handlers.clear # Remove all handlers, they are not reused anyway
        stopped
      end

      def sync(app)
        @app = app
        diff = handlers.size - app.connections
        return if diff == 0
        if diff > 0
          diff.times { decrement_handlers }
          Rapns::Daemon.logger.info("[#{app.name}] Stopped #{handlers_str(diff)}. #{handlers_str} remaining.")
        else
          diff.abs.times { increment_handlers }
          started # Make sure the feedback receiver is started if it has been stopped
          Rapns::Daemon.logger.info("[#{app.name}] Started #{handlers_str(diff)}. #{handlers_str} remaining.")
        end
      end

    end
  end
end

module Rapns
  module Daemon
    module Apns
      class AppRunner < Rapns::Daemon::AppRunner
        def started
          @feedback_receiver.stop if @feedback_receiver # Stop existing feedback receiver if present
          poll = Rapns.config[:feedback_poll]
          host, port = ENVIRONMENTS[app.environment.to_sym][:feedback]
          @feedback_receiver = FeedbackReceiver.new(app, host, port, poll)
          @feedback_receiver.start
        end
      end
    end
  end
end
```

**Comment by ileitch** [comment]
Hey, would you mind trying this now with master?

**Comment by koloritcm** [comment]
@ileitch Verified with master, thanks!
