### ISSUE TITLE
Rapns.push only sends one push notification

### ISSUE THREAD

**Issue by koloritcm** [ileitch/rapns#107]
From the Wiki:

"With your scheduler of choice, simply call Rapns.push. Rapns will start up, deliver all pending notifications and immediately shutdown."

This is not true. Because shutdown is called directly after start in Rapns.push function, the handler only sends one notification and then exits.

**Comment by koloritcm** [comment]
I fixed it by not letting the handler quit until the queue is empty when Rapns.config.push is true.

``` ruby
module Rapns
  module Daemon
    class DeliveryHandler
      def start
        @thread = Thread.new do
          loop do
            handle_next_notification
            break if @stop && !(Rapns.config.push && queue.size > 0)
          end
        end
      end
    end
  end
end
```

**Comment by ileitch** [comment]
I'm sorry I haven't addressed your issues yet, I will do as soon as I can thank. Thanks!

**Comment by koloritcm** [comment]
@ileitch No worries :) I understand if it is designed to only use long term connections, but I think there is not too much work to make it really nice to use with a scheduler as well. I have written in the comments how I solved the issues if that can give a hint on how to solve it. But they might be "hacks" so I guess you want to think through how to solve them smarter. I really like the gem, keep up the good work!

**Comment by ileitch** [comment]
Hey, would you mind trying this now with master?

**Comment by koloritcm** [comment]
@ileitch Verified with master, thanks!
