### ISSUE TITLE
Does GCM Payload limit include push token list?

### ISSUE THREAD

**Issue by davidjoliver** [ileitch/rapns#108]
I am trying to convert an app to take advantage of the multicast feature (attaching up to 1000 recipients to a single message). However the PayloadSizeValidator considers the entire structure of the request as the "payload". Therefore, the limit is reached well before 100 push tokens are attached (let alone a thousand) and the message is thus invalidated.

The verbiage in this post seems to refer only to the message itself.

http://developer.android.com/training/cloudsync/gcm.html#embed

Also: http://developer.android.com/google/gcm/gcm.html#request

The "fields" table in the second link only mentions the size limit within the "data" attribute section.

I'd be willing to implement a change to this if there is agreement about my interpretation.

**Comment by davidjoliver** [comment]
Never mind - 3.1 (from 1 month ago) has the fix

**Comment by ileitch** [comment]
Let me know if you run into any other issues.
