### ISSUE TITLE
MDM with Rapns

### ISSUE THREAD

**Issue by mwright78731** [ileitch/rapns#116]
In MDM, the device token is an unprintable binary string (unlike an alert APNS message) that, in my experience, must be passed to the Apple servers in that form.  Looking at the Rapns source, there appears to be no support for a binary device token.  Has Rapns ever been tested in a real MDM environment or is everyone making their own local changes for MDM support?

**Comment by ileitch** [comment]
I'm am unsure, MDM support was contributed a long time ago. I believe a few people have used it. Have you tried?

**Comment by mwright78731** [comment]
I was able to get it to work by overriding the Apns DeviceTokenFormatValidator, as well as changing the packing in the Apns Notification's to_binary when there is an MDM_KEY in the attributes_for_device.

**Comment by ileitch** [comment]
Can you point me to the documentation that explains the difference between a normal device token and an MDM token?

The normal token is also binary at first inception, most people just Base64 encode it. Rapns expects it to be  encoded in this way. Maybe you just need to encode the MDM token?

**Comment by mwright78731** [comment]
I'm glad I asked, I figured I was missing something.  I didn't realize the messaging token was received as NSData at the device.  As soon as I put the MDM token in the right form, it of course worked perfectly. Thanks for your time.

```
Mark
```

**Comment by ileitch** [comment]
You're welcome.
