### ISSUE TITLE
Older notifications continue to be sent

### ISSUE THREAD

**Issue by kitdesai** [ileitch/rapns#118]
I opened multiple connections to RAPNS and received multiple of the same notification. Once I got rid of the second connection (I'm now at one), I noticed that I'm receiving old notifications along with the newest one. 

Is this something that's the result of having multiple connections open in the past? Is this an issue others have seen?

**Comment by ileitch** [comment]
Do you see multiple log entries for the same ID?

**Comment by kitdesai** [comment]
So the issue seems to have resolved itself after a few days. Sorry to keep this issue open so long. 

I think it started with having multiple connections open. Not seeing old notifications being sent anymore.
