### ISSUE TITLE
Exception after kill -HUP when started without apps

### ISSUE THREAD

**Issue by dei79** [ileitch/rapns#119]
I'm starting the RAPNS daemon without any app. As soon the first user registers the app will be generated and my system sends the HUP message to the daemon. In this case I get the following exception:

[2013-03-23 11:12:53] [WARNING] You have not created an app yet. See https://github.com/ileitch/rapns for instructions.
[2013-03-23 11:13:31] [MY INSTANCE] Connected to gateway.push.apple.com:2195
[2013-03-23 11:13:31] [MY INSTANCE] Started, 1 handler.
/Users/dei79/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/rapns-3.1.0/lib/rapns/daemon/interruptible_sleep.rb:6:in `select': Invalid argument (Errno::EINVAL)
    from /Users/dei79/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/rapns-3.1.0/lib/rapns/daemon/interruptible_sleep.rb:6:in`interruptible_sleep'
    from /Users/dei79/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/rapns-3.1.0/lib/rapns/daemon/feeder.rb:30:in `block in feed_forever'
    from /Users/dei79/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/rapns-3.1.0/lib/rapns/daemon/feeder.rb:28:in`loop'
    from /Users/dei79/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/rapns-3.1.0/lib/rapns/daemon/feeder.rb:28:in `feed_forever'
    from /Users/dei79/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/rapns-3.1.0/lib/rapns/daemon/feeder.rb:16:in`start'
    from /Users/dei79/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/rapns-3.1.0/lib/rapns/daemon.rb:52:in `start'
    from /Users/dei79/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/rapns-3.1.0/bin/rapns:36:in`<top (required)>'
    from /Users/dei79/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bin/rapns:23:in `load'
    from /Users/dei79/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bin/rapns:23:in`<main>'

When I doing this when the service is started with an existing app this exception does not happen.

**Comment by ileitch** [comment]
Interesting. This is a consistent bug?
