### ISSUE TITLE
Feature Request: Change the rapns_notifications table name

### ISSUE THREAD

**Issue by smartcode** [ileitch/rapns#12]
As of now we have to use `rapns_notifications` as the 
table name in the database as this is defined in `Rapns::Notification` model

It would be nice to change this setting.

**Comment by ileitch** [comment]
Hi, I'm happy to implement this.. I'm just curious why you need to use a different table name?

**Comment by smartcode** [comment]
Hey thanks. 
I just thought it would be a nice feature to have. 
E.g. It would be more obvious to people that don't know the rapns gem to have a table called push_notifications or developers might want to use a table prefix in their database. 

Great gem anyway. Keep up the good work.

**Comment by ileitch** [comment]
OK, thanks for explaining. I think it's best to wait an see if any users have a real need for a different table name before I implement this. It is a nice idea, but the complexity it'll add to the setup process is something I want to avoid wherever possible. It'd require a config option to the migration generator, which would also then need to create a config/initializer to set the new table name on Rapns::Notification, as this model exists within Rapns and is not added directly to the Rails app by the generator.

Cheers
