### ISSUE TITLE
to long for god until pid file is generated

### ISSUE THREAD

**Issue by dei79** [ileitch/rapns#120]
On my server it took to long for god to register that the rapns daemon was started. This is because the pid file is written very late. At the end of the day I had several instances running of my server and this does not fit :-(

So I added the following transition handlers to your god configuration, feel free to take them over: 

``` ruby
  # determine when process has finished starting
  w.transition([:start, :restart], :up) do |on|
    on.condition(:process_running) do |c|
        c.running = true
        c.interval = 5.seconds
    end

    # failsafe
    on.condition(:tries) do |c|
        c.times = 5
        c.transition = :start
        c.interval = 5.seconds
    end
  end
```

**Comment by ileitch** [comment]
Yeah, there's not really an earlier place to write the PID file. The majority of startup time is spent loading the Rails environment. I'll import these changes, thanks.
