### ISSUE TITLE
Possible to de-coupone rapns from activerecord?

### ISSUE THREAD

**Issue by danielb2** [ileitch/rapns#121]
What if I'm using [sequel](http://sequel.rubyforge.org/) or [mongoid](http://mongoid.org/) ?  Or what if I don't want to have a database at all in the background. Is it possible to de-couple rapns altogether from using a storage mechanism?

**Comment by ileitch** [comment]
Sorry I somehow missed this. I'm afraid rapns is very tightly coupled with ActiveRecord currently. It is my intention to work toward decoupling in the future.

**Comment by ileitch** [comment]
Started work on this: https://github.com/ileitch/rapns/commit/7fb9e71468aaeff5376ca20470d0d02216f6defd

**Comment by danielb2** [comment]
:+1:

**Comment by ileitch** [comment]
I've released 3.3.0 with this ability. Instructions: https://github.com/ileitch/rapns/wiki/Implementing-your-own-storage-backend
