### ISSUE TITLE
Database field name issue (?¿)

### ISSUE THREAD

**Issue by kascote** [ileitch/rapns#127]
Hi,

I'm creating an admin interface using Rails 3.2.13 with Activeadmin and I'm having an issue with the 'type' field on rapns_app table.

For Rails the 'type' name is a reserve word used for table inheritance. When try to edit the record, ActiveRecord return an Rapns::Gcm::App object instead a the model object.

For example if I put any word that don't resolve to an object, like 'cocoom', Rails throw this error

> The single-table inheritance mechanism failed to locate the subclass: 'cocoom'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite MobilApp.inheritance_column to use another column for that information.

Is possible to change that field name ?

TIA
:: nelson

**Comment by ileitch** [comment]
I don't understand what you a try to achieve. `Rapns::App` is the base class which you do not use directly. `Rapns::Gcm::App` is the correct model. The other model is `Rapns::Apns::App`.
