### ISSUE TITLE
GCM asks for certificate

### ISSUE THREAD

**Issue by smoi** [ileitch/rapns#133]
I can't create a GCM app because it requires a certificate which is only for APN 

ctiveRecord::RecordInvalid: Validation failed: Certificate Certificate value must contain a certificate and a private key.
    from /Users/ste/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activerecord-3.2.12/lib/active_record/validations.rb:56:in `save!'

**Comment by aledelsur** [comment]
Hi, I am facing the same problem as you. Could you addressed the problem? Thanks in advance.

**Comment by ileitch** [comment]
I've made a change to ensure this doesn't happen, but really this shouldn't be happening anyway. The validation is only performed if something has been assigned to `certificate`.
