### ISSUE TITLE
Creating Rapns::Apns::App for custom environments.

### ISSUE THREAD

**Issue by michalorman** [ileitch/rapns#136]
Hi.

I have an application working perfectly on production environment. But we also need to deploy it into other environments. Is there any reason that Rapns::Apns::App validates inclusion of environment in development, production and sandbox? Currently as a workaround we disable validations when saving Rapns::Apns::App model.

Is there any way to create app for other environments (which I failed to find)?
Thanks in advance!

**Comment by ileitch** [comment]
That field is the APNs environment (dev and sandbox are the same, dev only there for backwards compatability). The Rails env is given as an argument on the command line.
