### ISSUE TITLE
Rapns migration add_gcm won't work with Mysql2

### ISSUE THREAD

**Issue by thebucknerlife** [ileitch/rapns#137]
Hi,

I'm installing rapns into a rails app for APNS. Can't migrate the files generated by "rails g rapns" because add_gcm sets a default for the :certificate attribute.

The error:

``` ruby
Mysql2::Error: BLOB/TEXT column 'certificate' can't have a default value: ALTER TABLE `rapns_apps` CHANGE `certificate` `certificate` text DEFAULT '' NOT NULL/Users/Greg/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `query'
```

Mysql2 doesn't support setting a default for Blob or Text columns.

Additionally, getting a duplicate column error for :type, but I think that might be an error on my part from trying the migrations over and over again.

Is this a bug? Known solution for this? Thanks!

note: I first posted a question on SO for this issue, thinking it was my error. Feel free to take a look for more detail: http://stackoverflow.com/questions/17224763/migration-fails-for-rapns-gem-with-mysql2

Thank you!
Greg

**Comment by ileitch** [comment]
That's an MySQL error, not the MySQL2 gem. What MySQL version are you using?

**Comment by thebucknerlife** [comment]
Thanks for the clarification. From terminal $ mysql => "Server version: 5.6.10 Source distribution"

**Comment by ileitch** [comment]
Can you please try master?

`gem 'rapns', :github => 'ileitch/rapns'`
