### ISSUE TITLE
Feature Request: Auto Detect Certificate Expiry

### ISSUE THREAD

**Issue by tobinharris** [ileitch/rapns#142]
Hi folks

Rapns is ace, thanks for the great work.

I was thinking it would be ace if Rapns could detect expired certificates (pems) and mark this as the failed delivery reason, or perhaps output something to the logs. 

We just had a certificate expire and it took me a few hours to diagnose why push messages weren't getting out.

It's a NICE-TO-HAVE feature :)

Tobin

**Comment by ileitch** [comment]
I'm working on this, though I'm not sure exactly how the APNs responds to an expired certificate. Did you see any errors in the log?

**Comment by tobinharris** [comment]
Cool. Strangely I didn't see anything in the Heroku logs. 

Is there a separate log for background tasks?

Looking at the [APNS docs](http://developer.apple.com/library/ios/#technotes/tn2265/_index.html):

"If you can't even open a connection to APNs, perhaps your APNs TLS/SSL certificate has expired. These certificates are valid for one year but production APNs certificates can be renewed at any time."

I can test this when I get to work.

T

**Comment by ileitch** [comment]
Yes, I expect it manifests as an OpenSSL error. Those should already be caught and logged in log/rapns.log.

What version are you using?

You can catch internal errors using `on.error` with the reflection API - https://github.com/ileitch/rapns/wiki/Reflection-API

**Comment by tobinharris** [comment]
I'm on 2.x. I see it in the rapns log on startup. It says:

```
OpenSSL::SSL::SSLError, SSL_connect returned=1 errno=0 state=SSLv3 read finished A: sslv3 alert certificate expired
```

So, I guess that's pretty good visible FAIL :)

I'd be interested to know how to setup our devops to signal if this happens again. 

BTW, I still get that error after renewing the certificate and regenerating following instructions on the WiKi. Is there anything we need to do with the CA certificate?

**Comment by ileitch** [comment]
Thanks for the error.

To catch these errors you need to upgrade to 3.x and implement the `error` hook I mentioned earlier. I'll also be adding another hook soon which will fire when the cert comes within one month of expiry. Please refer to the [upgrading notes](https://github.com/ileitch/rapns/wiki/Upgrading-from-version-2.x-to-3.0).

I'm not sure why the new cert is not working - are you sure you replaced to old one in Rapns::App#certificate? You can check the expiry date like this:

``` ruby
cert = OpenSSL::X509::Certificate.new(app.certificate)
p cert.not_after
```

**Comment by tobinharris** [comment]
Thanks lleitch

The expiry and certificate details all look good.

<pre>
#<OpenSSL::X509::Certificate subject=#<OpenSSL::X509::Name:0x007fbb9415c500>, issuer=#<OpenSSL::X509::Name:0x007fbb9415c348>, serial=#<OpenSSL::BN:0x007fbb9415c140>, not_before=2013-07-15 18:35:40 UTC, not_after=2014-07-15 18:35:40 UTC>
</pre>

Interestingly it works on local, but not on Heroku. Both use the same certificate (we have our Heroku dev server run in using the development PEM)

One of the guys said he tried a SSL connect on the Heroku console which worked, using Rapns code...

> [15/07/2013 22:54:51] Muneeb: rapns uses following code to connect to apple sandbox. I have ran it line by line on the console and it didn't throw any error:
> 
> https://github.com/ileitch/rapns/blob/master/lib/rapns/daemon/apns/connection.rb#L96
> 
> [15/07/2013 22:55:20] Muneeb: it should throw an exception on line#109 

Very strange that it's connecting on the heroku console, but not in the app. Logs are still showing the error when sending the push.

We've upgraded to 3.3.2. 

Now seeing error more often :)

```
2013-07-15T22:07:34.164378+00:00 app[rapns.1]: /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.3.2/lib/rapns/daemon/apns/connection.rb:109:in `connect'
2013-07-15T22:07:34.164378+00:00 app[rapns.1]: /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.3.2/lib/rapns/daemon/apns/connection.rb:109:in `connect_socket'
2013-07-15T22:07:34.164378+00:00 app[rapns.1]: /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.3.2/lib/rapns/daemon/apns/connection.rb:26:in `connect'
2013-07-15T22:07:34.164378+00:00 app[rapns.1]: /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.3.2/lib/rapns/daemon/apns/delivery_handler.rb:29:in `connection'
2013-07-15T22:07:34.164378+00:00 app[rapns.1]: /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.3.2/lib/rapns/daemon/apns/delivery_handler.rb:17:in `deliver'
2013-07-15T22:07:34.164378+00:00 app[rapns.1]: /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.3.2/lib/rapns/daemon/delivery_handler.rb:39:in `handle_next_notification'
2013-07-15T22:07:34.164378+00:00 app[rapns.1]: /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.3.2/lib/rapns/daemon/delivery_handler.rb:11:in `block (2 levels) in start'
2013-07-15T22:07:34.164378+00:00 app[rapns.1]: /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.3.2/lib/rapns/daemon/delivery_handler.rb:10:in `loop'
2013-07-15T22:07:34.164378+00:00 app[rapns.1]: /app/vendor/bundle/ruby/1.9.1/gems/rapns-3.3.2/lib/rapns/daemon/delivery_handler.rb:10:in `block in start'
2013-07-15T22:07:34.328031+00:00 app[rapns.1]: [2013-07-15 22:07:34] [ERROR] OpenSSL::SSL::SSLError, SSL_connect returned=1 errno=0 state=SSLv3 read finished A: sslv3 alert certificate expired
```

The mystery continues...

T

**Comment by ileitch** [comment]
What Rails environment are you starting Rapns with? Are you also using that same environment when you started a console on Heroku?

Do you have multiple apps? Did you update certificates for all?

**Comment by ileitch** [comment]
Also you need to restart rapns after updating the certificate.

**Comment by tobinharris** [comment]
Thanks for the ongoing help! 

Our Heroku process starts with

```
bundle exec rapns development -f
```

We only do this to use the development.pem

If we want to use production.pem we do

```
bundle exec rapns production -f
```

The Rails app web site itself runs under production.

Yes, we've tested local development environment and production environments on our local machines, no problems. This is with the new development.pem and production.pem files.

We are restarting Rapns after updates, but no cigar.

It's one app currently.

**Comment by tobinharris** [comment]
OMG.

We are idiots.

Because our app can have multiple certificates, we did this in our seeds.rb.

app = Rapns::App.find(some_id)
app.certificate = File.read("config/rapns/some_id/#{ENV['ERA_ENV']}.pem")

And that code never gets run again. Which means the certificate never gets imported again.

facepalm

Sorry for wasting your time, and thanks for the help.

**Comment by ileitch** [comment]
Try this snippet Heroku in both your development and production environments, hopeully it'll raise an error for the offending app.

``` ruby
require 'rapns'
Rapns.require_for_daemon

HOSTS = {
  :production  => ['gateway.push.apple.com', 2195],
  :development => ['gateway.sandbox.push.apple.com', 2195], # deprecated
  :sandbox     => ['gateway.sandbox.push.apple.com', 2195]
}

Rapns::Apns::App.all.each do |app|
  host, port = HOSTS[app.environment.to_sym]
  connection = Rapns::Daemon::Apns::Connection.new(app, host, port)
  connection.connect
end
```

The only other cause I can think of is because your certificate is so new. What time zone does your app use on Heroku? Perhaps a Ruby/OpenSSL bug is confused by the not_before time zone.

**Comment by ileitch** [comment]
Ah! Great, glad you found the cause. I'll leave this issue open for now while I'm working on expiry warnings.

**Comment by tobinharris** [comment]
Thanks for the snippet, useful to see how you'd test the connection.

Out of interest, at what point in your app lifecycle would you load the certificate into the database? Do you do this through a GUI or a file?

T

**Comment by shawndeprey** [comment]
Great thread, I ran into this issue and this thread made it clear what the fix was. :+1:

**Comment by tobinharris** [comment]
Welcome. 

It's served me well too - a year later I ran in to the same problem, had totally forgotten I had started this thread and found the problem. Cry.

My certificate go-live README has been duly updated :)
