### ISSUE TITLE
rails 2 compatibility

### ISSUE THREAD

**Issue by intouchmvc** [ileitch/rapns#143]
I have a rails 2 app that will likely take several months to update to rails 3, is there any chance to get ranps running.

**Comment by ileitch** [comment]
Have you tried it? I don't think it'll be too hard to support Rails 2, though I haven't tried myself.

**Comment by intouchmvc** [comment]
I could not get the generator to run, so I tried making a dummy rails 3 app and running the generator then copying the migrations and initializer. But rake db:migrate fails and the app will not boot locally.

Gem.source_index called from /Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/rails-2.3.16/lib/rails/gem_dependency.rb:21.
/Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/activesupport-2.3.16/lib/active_support/dependencies.rb:469:in `load_missing_constant': uninitialized constant Rapns (NameError)
    from /Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/activesupport-2.3.16/lib/active_support/dependencies.rb:106:in`const_missing'
    from /Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/activesupport-2.3.16/lib/active_support/dependencies.rb:118:in `const_missing'
    from /Users/jeffreyrossi/svn/discount_vfs/config/initializers/rapns.rb:4
    from /Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/activesupport-2.3.16/lib/active_support/dependencies.rb:173:in`load_without_new_constant_marking'
    from /Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/activesupport-2.3.16/lib/active_support/dependencies.rb:173:in `load'
    from /Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/rails-2.3.16/lib/initializer.rb:622:in`load_application_initializers'
    from /Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/rails-2.3.16/lib/initializer.rb:621:in `each'
    from /Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/rails-2.3.16/lib/initializer.rb:621:in`load_application_initializers'
    from /Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/rails-2.3.16/lib/initializer.rb:176:in `process'
    from /Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/rails-2.3.16/lib/initializer.rb:113:in`send'
    from /Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/rails-2.3.16/lib/initializer.rb:113:in `run'
    from /Users/jeffreyrossi/svn/discount_vfs/config/environment.rb:24
    from /Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/activesupport-2.3.16/lib/active_support/dependencies.rb:182:in`require'
    from /Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/activesupport-2.3.16/lib/active_support/dependencies.rb:182:in `require'
    from /Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/activesupport-2.3.16/lib/active_support/dependencies.rb:547:in`new_constants_in'
    from /Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/activesupport-2.3.16/lib/active_support/dependencies.rb:182:in `require'
    from /Users/jeffreyrossi/.rvm/gems/ree-1.8.7-2012.02@discount/gems/rails-2.3.16/lib/commands/server.rb:84
    from script/server:4:in`require'
    from script/server:4

**Comment by ileitch** [comment]
I don't really have time to work on Rails 2 support myself, as it's a very infrequently requested feature. I'll gladly review a pull request should you decide to work on it yourself.
