### ISSUE TITLE
How to recover from downtime

### ISSUE THREAD

**Issue by tobinharris** [ileitch/rapns#144]
Hi folks

We have a RAPNS installation that's been offline for 4 days. None of our notifications were being delivered due to an expired certificate. (delvered == false)

How do we start RAPNS again but NOT deliver the old mesages.

We've now upgraded to the latest version of RAPNS btw.

Tobin

**Comment by ileitch** [comment]
You can either delete the unwanted notifications, mark them as delivered or as failed. Using a migration should be simple enough.
