### ISSUE TITLE
No pid file?

### ISSUE THREAD

**Issue by paulwalker** [ileitch/rapns#145]
I am trying to get monit setup for rapns, but for whatever reason, no pid file is being written.  Some of the configuration:

```
 config.foreground = false
 config.pid_file = 'tmp/pids/rapns.pid'
 config.logger = Logger.new('log/rapns.log', 0, 5242880)
```

I am using the command `bundle exec rapns production` to start rapns.  The configuration seems to be read because I am getting log message in the logger I have set up.

So, why can't I find a pid file at tmp/pids/rapns.pid?  I know it's not a permissions issue...thx.

**Comment by ileitch** [comment]
What version are you using?

Do you see any errors in the log?
Try `bundle exec rapns production --foreground` do you see any errors?

In your rapns.rb, print out config.pid_file right after you assign it. Rapns has some logic to turn relative paths absolute ones, perhaps the pid is being written to another location?

``` ruby
Rapns.configure do |config|
  config.pid_file = 'tmp/pids/rapns.pid'
  STDERR.puts config.pid_file
end
```

**Comment by paulwalker** [comment]
thx, will do it's version `3.3.2`

**Comment by paulwalker** [comment]
Using pry I outputted the #pid_file and it is the correct location `=> "/Users/paul/Projects/myapp/tmp/pids/rapns.pid"`

Starting the app in the foreground and the output is normal:

```
[ec2-user@ip-x-x-x-x current]$ bundle exec rapns production --foreground
[2013-07-20 21:55:42] [myapp_ios] Started, 10 handlers.
[2013-07-20 21:55:42] [myapp_android] Started, 10 handlers.
[2013-07-20 21:55:42] [myapp_ios] Connected to feedback.push.apple.com:2196
[2013-07-20 21:56:43] [myapp_ios] Connected to feedback.push.apple.com:2196
```

I did get a pid using the -p option with and without the --foreground option.  So, this issue seems to be specific to setting the pid file in #configure.  

Also, how do I properly stop the service?  A normal kill or kill -INT does not seem to do the trick, only kill -9.  I can't find anything on the documentation for this either.

**Comment by paulwalker** [comment]
Hold the press, false alarm.  The code wasn't updated on the server as I thought it was.  The pid file is showing up now, wonderful.  

However, monit shows the process as `not monitored` after successfully starting it up.  Here is the monit configuration I am using:

```
check process rapns with pidfile /myapp/shared/tmp/pids/rapns.pid
  start program = "/bin/su - ec2-user -c 'cd /myapp/current && bundle exec rapns production'" as uid root with timeout 90 seconds
  stop program = "/bin/su - ec2-user -c 'cd /myapp/current && bundle exec kill /myapp/shared/tmp/pids/rapns.pid >> /myapp/current/log/rapns.pid 2>&1'" as uid root with timeout 90 seconds
  group rapns
```

Do I need to run the app in the foreground in order to have monit monitor this?  Also, a normal `kill` command is not successfully stopping it.  I am still forced to use -9.

**Comment by ileitch** [comment]
I'm unsure why the monit state is "not monitored" - it's possible it got a little confused. Do you have two rapns processes running perhaps?

Your stop command may not be correct - I've not seen `kill` accept a file path before.

As for why it's not stopping... try these steps:
- First, disable monit so it does not interfere while testing.
- Start rapns manually with --foreground.
- Signal with USR2 to get some debug (post it here).
- Signal with INT, now look for "Shutting down..." - does the process hang after printing this?

**Comment by paulwalker** [comment]
`bundle exec` has a kill command that takes a file path argument.  Ok, this is my fault...the symlink to the tmp directory has not been setup and consequently the `with pidfile` is pointing to a different location.  Let me correct that and ensure everything is OK and I will close this.  Appreciate your attentiveness on a Sat :+1:

**Comment by stevesng** [comment]
you can use the `cat` command on the pidfile (e.g. cat /myapp/shared/tmp/pids/rapns.pid) and pass the value to the `kill` command.

**Comment by paulwalker** [comment]
I sitll can't get monit to properly monitor a rapns process.  I have to `sudo monit unmonitor rapns` and then `sudo monit monitor rapns` in order to get the status to properly display as `running`

It would be great if the documentation could mention how to properly stop a rapns process.  The only effective method I have found is to use kill -9.

These issues are obviously unrelated to the original topic, so I will close this.
