### ISSUE TITLE
notification_delivered called twice?

### ISSUE THREAD

**Issue by sdossick** [ileitch/rapns#149]
Hi there

I'm seeing the "notification_delivered" callback on the Rapns.reflect call being called twice for each notification.  It looks like it gets called both on

lib/rapns/daemon/delivery.rb (line 21 inside of mark_delivered) and

lib/rapns/daemon/delivery_handler.rb (line 40 inside of handle_next_notification)

I'm guessing it's meant only to be called from one of those places?

Thanks for the excellent work on this project!  A huge timesaver.

**Comment by sandro** [comment]
I'm seeing the same thing.
