### ISSUE TITLE
MDM explanation please

### ISSUE THREAD

**Issue by eyaleizenberg** [ileitch/rapns#150]
Hi,
After installing the mdm profile on an iphone and successfully getting the following 5 parameters from the device: "PushMagic", "Token", "Topic", "UDID", "UnlockToken"

It is unclear to me how to initiate an mdm connection with the device using this gem.

Thanks for the help.

**Comment by ileitch** [comment]
I have never used MDM myself, but others do use rapns with MDM. As far as I'm aware you need to assign the push magic on the notification - https://github.com/ileitch/rapns/wiki/Advanced-APNs-Features

**Comment by eyaleizenberg** [comment]
I've seen that page before opening the issue, but it did not help me...
