### ISSUE TITLE
"`attr_accessible': `attr_accessible` is extracted out of Rails into a gem" error.

### ISSUE THREAD

**Issue by novikserg** [ileitch/rapns#153]
I am using Rails v3.2.9 and Ruby v2.0.0.
When I execute 'rapns development' I get the following error:

<pre>
`attr_accessible': `attr_accessible` is extracted out of Rails into a gem. Please use new recommended protection model for params(strong_parameters) or add `protected_attributes` to your Gemfile to use old one. (RuntimeError)
</pre>

What am I doing wrong?
Here is my Gemfile:
<b>gem 'rapns', :github => 'ileitch/rapns'</b>

**Comment by mattconnolly** [comment]
Are you sure you are using rails version 3?

Perhaps you have rails 4 installed. Try doing `bundle exec rapns` to use the version of rails specified by your Gemfile.
