### ISSUE TITLE
Message send always gets error code 8 (Invalid Token)

### ISSUE THREAD

**Issue by adamrhunter** [ileitch/rapns#16]
hi There,
  I have rapns running and it seems to work intermittently.  I've noticed that the error_code is nearly always set to 8, even though the message is delivered. (the delivered_at and failed_at are the same time).  furthermore, i can't locate the method that is writing the error to the database.  all debugging i have shows that the Notification Object is being saved in a "successful" state in the deliver method of the DeliveryHandler class.

any hints on how to get around this?

thanks,

adam.

**Comment by ileitch** [comment]
Interesting. Are the messages always delivered? Usually error 8 indicates that you are using a development device token on the production APN service, or vise versa.

A Rapns::DeliveryError is raised in connection.rb and rescued in delivery_handler.rb

**Comment by ileitch** [comment]
Closing due to lack of feedback.
