### ISSUE TITLE
Reflection API on.notification_failed

### ISSUE THREAD

**Issue by edgarhenriquez** [ileitch/rapns#161]
Hi, I'm trying to use the Reflection API to handle failed GCM notifications.

For example, I want to remove the device when I receive a "NotRegistered" error from the GCM server, so I need the device_token for each failed notification.

So when a notification delivery fails, the method `on.notification_failed` is called but the notification has the failed field set to false and the failed_at, device_token, error_code and error_description fields set to nil. Is it a bug or just the expected behaviour?

I'm using rapns 3.4.1

Thanks

**Comment by ileitch** [comment]
Thanks, I see the problem. I wont be able to fix this for a few days, you can downgrade to 3.3.2 until it's fixed.

**Comment by edgarhenriquez** [comment]
Cool, thanks
