### ISSUE TITLE
New to ROR , Kill rapns foreground process

### ISSUE THREAD

**Issue by zanderisrael** [ileitch/rapns#168]
I got everything running, problem is i want to kill the rapns process, and on the other hand tap back in to the running process feed with ssh. 

is this even possible ?

**Comment by zanderisrael** [comment]
Getting this:

root@mx:/var/servers/myapp# rails g rapns
    conflict  config/initializers/rapns.rb
Overwrite /var/www/sites/zanderisrael/appzander.com/subdomains/ruby/servers/pazam/config/initializers/rapns.rb? (enter "h" for help) [Ynaqdh] 

Why? 
I want to configure 'rapns.rb' from ssh. 

Is there another way? a step by step guide will really help.

**Comment by mattconnolly** [comment]
1. If you want to kill rapns, you can use the `kill` command. Find the process id with the `ps` command.
2. The conflict you see is common with any rails generator that creates a file when that file already exists. If you want to create a new configuration file from scratch, delete or rename the existing one and run the generator again. Then you can edit the config file yourself.

Also, you should not be running your rails app or generators as root.

**Comment by mattconnolly** [comment]
If rapns is running as a foreground process, you can kill it with CTRL+C. This is common in all unix-like operating systems and is not specific to rails, ruby or rapns. Good luck!

**Comment by zanderisrael** [comment]
Thank you ! 
When i log in to ssh i type "source etc/profile"
This loads rails .

If i dont do this i can get rails comman not found ... Or somthing like that.

Im on a mac connected thru terminal.
