### ISSUE TITLE
kill -SIGTERM PID

### ISSUE THREAD

**Issue by zanderisrael** [ileitch/rapns#177]
From what i understand from this code : 
 rapns / lib / rapns / daemon.rb
# 

def self.setup_signal_traps
      @shutting_down = false

```
  Signal.trap('SIGHUP') { AppRunner.sync }
  Signal.trap('SIGUSR2') { AppRunner.debug }

  ['SIGINT', 'SIGTERM'].each do |signal|
    Signal.trap(signal) { handle_shutdown_signal }
  end
end
```
# 

I can gracefully shutdown the daemon by calling this:

kill -SIGTERM `pidof rapns`

When i call it from root with ssh , it works , yet no shutdown message is shown.
When i call it from my rails controller:

system("kill -SIGTERM `pidof rapns`") 

It has no effect.

i noticed that if the queue was empty and no sending happend the kill command worked from the rails controller...

Am i doing things wrong?

**Comment by mattconnolly** [comment]
I believe the system command should be 'kill -TERM <pid>'

**Comment by zanderisrael** [comment]
Still a no go :(, its not killing the daemon.

**Comment by ileitch** [comment]
Did you manage to figure out what was wrong here?
