### ISSUE TITLE
add notification table

### ISSUE THREAD

**Issue by GuoYangguang** [ileitch/rapns#187]
Beside rapns_notifications table , is it possible to create another table to store message when using the rapnas gem? thanks!

**Comment by mattconnolly** [comment]
The rapns gem specifically looks for messages to send in the rapns_notifications table. Do you want a different table name or to pull messages from multiple tables?

If you just want to change the table name, you can set this on `Rapns::Notification.table_name = "other_table_name"` in an initialiser that will be loaded during the rapns startup phase.

If you want multiple tables, you will need to extend the code yourself.

**Comment by ileitch** [comment]
@GuoYangguang what are you trying to achieve?

**Comment by GuoYangguang** [comment]
@mattconnolly , thanks, :)

**Comment by GuoYangguang** [comment]
@ileitch, thanks, if i have question later, i will ask your help, currently i am learning it.
