### ISSUE TITLE
Support for Splitting Pushes into Pieces

### ISSUE THREAD

**Issue by blakewatters** [ileitch/rapns#19]
I have developed some custom support for taking a single large message and delivering it in multiple notifications. If there's interest, I'd be happy to extract it from GateGuru into an rapns API. I'm thinking something like:

``` ruby
Rapns::Notification.deliver_long_alert!(long_alert_text, :device_token => 'whatever'
```

Or whatever API makes the most sense

**Comment by ileitch** [comment]
I'm not opposed to more 'exotic' features such as this, just so long as we can keep them separate from the core functionality. In this case I'd probably opt for a Factory pattern rather than a method on Notification.

I'm curious, what do you use this for exactly? The general consensus is to use the notification to trigger a web request if the payload is too big for a notification.

**Comment by blakewatters** [comment]
We are using this during delivery of flight status push notifications for
GateGuru (http://www.gateguruapp.com/). We pull flight status information
from a third party API and there's no guarantee of how many field updates
you will see in a given payload. Furthermore, its difficult to know the
significance of any particular changes in the history for a given user
(someone on a flight won't necessarily care if landing shifts back by 10
mins, but someone on the ground might leave 10 mins later to head to the
airport). We build a human readable version of the flight status attribute
changes when we digest the payload, which can easily span 2 push
notifications if a bunch of info is updated as well. In these cases, we
just want to split the message across 2 push notifications and let the user
get the entire news.

On Thu, Dec 8, 2011 at 2:38 PM, Ian Leitch <
reply@reply.github.com

**Comment by ileitch** [comment]
Oh I see, I thought you were using it as a means to deliver some kind of non-user visible payload.

The main issue I see that the the way in which the alert message should be split up would be very subjective. Rapns knows nothing of the alert context and would only be able to split based on the number of bytes; resulting in broken sentences, or something to that effect.

I think instead we should just expose the notification byte size to the user and let them split the alert in a way that suits them?

**Comment by blakewatters** [comment]
That works the crux of my changes are to expose the size easily. I could
throw together a snippet for the wiki page for how to split if that's
helpful.

On Thu, Dec 22, 2011 at 10:47 AM, Ian Leitch <
reply@reply.github.com

**Comment by ileitch** [comment]
Yeah that'd be great, thanks.

**Comment by ileitch** [comment]
The payload size is now exposed by the notification, see a380c03ae3.
