### ISSUE TITLE
Notifications Delivered Multiple Times

### ISSUE THREAD

**Issue by blakewatters** [ileitch/rapns#20]
Moving this from #18 as a standalone issue. We are seeing duplicated delivery of notifications due to a race with the Feeder.

Note that this is happening pretty regularly for me on GateGuru.

**Comment by ileitch** [comment]
OK, this fixes the problem (and removes some nasty threading code to boot). I've sent hundreds of notifications to my phone without any duplicates. Please give master a try and i'll cut a new release.

/cc @mobits

**Comment by blakewatters** [comment]
Thanks for the quick turn on this @ileitch. I am deploying to production now to verify.

**Comment by blakewatters** [comment]
I just saw a duplicate push go by:

```
2011-12-08T21:43:10+00:00 app[rapns.1]: [2011-12-08 21:43:10] Notification 562 delivered to 485e789edc6765c6928fbccf039688587bdd301daa9c7e52c5571583a97ebe3d
2011-12-08T21:43:11+00:00 app[rapns.1]: [2011-12-08 21:43:11] Notification 562 delivered to 485e789edc6765c6928fbccf039688587bdd301daa9c7e52c5571583a97ebe3d
```

**Comment by ileitch** [comment]
Pretty sure this is fixed by 64aafcf6cd now.

**Comment by mobits** [comment]
I was having the same problem and now it seems to be fixed.

**Comment by fredriproad** [comment]
I, too, had this problem in production and just upgraded. So far, so good. Thanks Ian, Blake and company!
