### ISSUE TITLE
Segmentation fault when running in foreground

### ISSUE THREAD

**Issue by seenickcode** [ileitch/rapns#21]
Hi there.  

Two questions:

1)  I'm afraid I'm getting a segmentation fault when running rapns in the foreground.  It looks like it's occurring when connecting to the apple dev gateway (trace below).  

2)  On the other hand, when I tried to run the daemon in the background, I do see (albeit only 2x) entries saying I'm connected to the gateway.  Strange thing is that if I re-run the background daemon more times I don't see anymore log entries that I have connected (again, only 2 log entries).

I'm using Ruby 1.9.2.

Trace for 1)    (above):

<pre><code>
$ bundle exec rapns development --foreground
/Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon/connection.rb:80: [BUG] Segmentation fault
ruby 1.9.2p290 (2011-07-09 revision 32478) [x86_64-darwin11.0.1]

-- control frame ----------
c:0016 p:---- s:0053 b:0053 l:000052 d:000052 CFUNC  :connect
c:0015 p:0136 s:0050 b:0050 l:000049 d:000049 METHOD /Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon/connection.rb:80
c:0014 p:0023 s:0045 b:0045 l:000044 d:000044 METHOD /Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon/connection.rb:14
c:0013 p:0013 s:0042 b:0042 l:000041 d:000041 METHOD /Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon/delivery_handler.rb:27
c:0012 p:0012 s:0039 b:0039 l:000038 d:000038 METHOD /Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon/delivery_handler_pool.rb:12
c:0011 p:0042 s:0035 b:0035 l:000025 d:000034 BLOCK  /Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon/pool.rb:13
c:0010 p:---- s:0031 b:0031 l:000030 d:000030 FINISH
c:0009 p:---- s:0029 b:0029 l:000028 d:000028 CFUNC  :times
c:0008 p:0013 s:0026 b:0026 l:000025 d:000025 METHOD /Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon/pool.rb:10
c:0007 p:0297 s:0023 b:0023 l:000022 d:000022 METHOD /Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon.rb:46
c:0006 p:0180 s:0018 b:0018 l:002270 d:002270 TOP    /Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/bin/rapns:28
c:0005 p:---- s:0013 b:0013 l:000012 d:000012 FINISH
c:0004 p:---- s:0011 b:0011 l:000010 d:000010 CFUNC  :load
c:0003 p:0127 s:0007 b:0007 l:002198 d:0002c0 EVAL   /Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/bin/rapns:19
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:0000 s:0002 b:0002 l:002198 d:002198 TOP   
---------------------------
-- Ruby level backtrace information ----------------------------------------
/Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/bin/rapns:19:in `<main>'
/Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/bin/rapns:19:in `load'
/Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/bin/rapns:28:in `<top (required)>'
/Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon.rb:46:in `start'
/Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon/pool.rb:10:in `populate'
/Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon/pool.rb:10:in `times'
/Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon/pool.rb:13:in `block in populate'
/Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon/delivery_handler_pool.rb:12:in `object_added_to_pool'
/Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon/delivery_handler.rb:27:in `start'
/Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon/connection.rb:14:in `connect'
/Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon/connection.rb:80:in `connect_socket'
/Users/smthmarketable/.rvm/gems/ruby-1.9.2-head/gems/rapns-1.0.1/lib/rapns/daemon/connection.rb:80:in `connect'

-- C level backtrace information -------------------------------------------

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6
</code></pre>

Any ideas?

**Comment by ileitch** [comment]
It may be that you've somehow linked against two versions of openssl.

Are you using mysql2 or pg? Please see this gist comment and do the same.

**Comment by ileitch** [comment]
Sorry I forgot to add the gist link. I found this blog post that will possibly help you out more though.

http://www.christopherirish.com/2011/09/02/ruby-1-9-2-segmentation-fault-and-openssl/
