### ISSUE TITLE
can't run this on Heroku

### ISSUE THREAD

**Issue by chrischenyc** [ileitch/rapns#22]
Hi there,

First thing first, I tested rapns on my local machine, all good. The things is I'm new to RoR (I'm an iOS dev) and I'm hosting the server-side code on Heroku.

Issue: I wanted to run following on Heroku
bundle exec rapns <Rails environment>

I understand this step is to kick start a background daemon which check the database for new notification to deliver periodically. I used following command:
heroku run bundle exec rapns production --foreground

which gave me:
Running bundle exec rapns production --foreground attached to terminal... up, run.3
[WARNING] Detected Rails 3.1.1, patching PostgreSQLAdapter to fix reconnection bug: https://github.com/rails/rails/issues/3160
/app/.bundle/gems/ruby/1.9.1/gems/rapns-1.0.1/lib/rapns/daemon.rb:95:in `initialize': No such file or directory - /app/tmp/pids/rapns.pid (Errno::ENOENT)
    from /app/.bundle/gems/ruby/1.9.1/gems/rapns-1.0.1/lib/rapns/daemon.rb:95:in`open'
    from /app/.bundle/gems/ruby/1.9.1/gems/rapns-1.0.1/lib/rapns/daemon.rb:95:in `write_pid_file'
    from /app/.bundle/gems/ruby/1.9.1/gems/rapns-1.0.1/lib/rapns/daemon.rb:43:in`start'
    from /app/.bundle/gems/ruby/1.9.1/gems/rapns-1.0.1/bin/rapns:28:in `<top (required)>'
    from /app/.bundle/gems/ruby/1.9.1/bin/rapns:19:in`load'
    from /app/.bundle/gems/ruby/1.9.1/bin/rapns:19:in `<main>'

So it's something about .pid file. I read the readme, it's set to blank in rapns.yml. I couldn't go further, please help me.

My email is chrischen79@gmail.com

Thank you very much!!!

**Comment by ileitch** [comment]
You say `pid_file` is blank on your rapns.yml. Can you please confirm this, from the error given I can see it is still set to 'tmp/pids/rapns.pid'.

**Comment by chrischenyc** [comment]
Yes, I didn't change anything in the rapns.yml file, here's what's in the file:

development:
  certificate: development.pem
  certificate_password:

  push:
    host: gateway.sandbox.push.apple.com
    port: 2195
    poll: 2
    connections: 3

  feedback:
    host: feedback.sandbox.push.apple.com
    port: 2196
    poll: 60

production:
  certificate: production.pem
  certificate_password:
  airbrake_notify: true
  pid_file: tmp/pids/rapns.pid

  push:
    host: gateway.push.apple.com
    port: 2195
    poll: 2
    connections: 3

  feedback:
    host: feedback.push.apple.com
    port: 2196
    poll: 60

**Comment by blakewatters** [comment]
This will execute fine on Heroku -- been running fine for months. You need to remove the pid_file: configuration from your YAML

**Comment by ileitch** [comment]
I'd like to improve the experience of using rapns on Heroku. I've never used it myself so I'm not sure what may help.
- Does Heroku not allow filesystem writes at all? Or is there a writeable directory somewhere?
- Is it even possible to use the PID (with God, monit, etc.) file if we were able to write it?
- Is there a way for rapns to detect if it is being run in Heroku?

**Comment by blakewatters** [comment]
Ian -

The best thing for you to do is just to create a Heroku app under the Cedar
stack and execute it yourself (it's free). In my experience, all you need
to do to get a first class Heroku experience is to remove the pid_file line
from the config file and run it from the Procfile like so:

rapns: bundle exec rapns $RACK_ENV -f

The log output will be picked up from stout and aggregated and RACK_ENV
will be configured as appropriate for the running instance. In face, we
should probably just start with a wiki page instructing folks to take those
very steps.
- Blake

On Thu, Dec 22, 2011 at 10:41 AM, Ian Leitch <
reply@reply.github.com
