### ISSUE TITLE
Rapns won't write to log file in production

### ISSUE THREAD

**Issue by mobits** [ileitch/rapns#23]
Hi,

I notice that rapns, in production environment (Ubuntu), is creating the log file when I start the service but isn't writing to it.

I checked the file permissions and everything seem to be fine.

In development environment (Mac OS),  the log file is ok.

Here is my log directory in production

```
drwxrwxr-x 2 mob mob    4096 2011-12-16 16:04 ./
drwxrwxr-x 6 mob mob    4096 2011-08-11 23:13 ../
-rw-r--r-- 1 mob mob     621 2011-11-25 21:22 development.log
-rw-r--r-- 1 mob mob 3923116 2011-12-16 16:07 production.log
-rw-r--r-- 1 mob mob       0 2011-12-16 16:04 rapns.log
```

Any ideas?

**Comment by ileitch** [comment]
Only errors are logged in production.

**Comment by smoi** [comment]
is there a way to enable it even in production?

**Comment by ileitch** [comment]
@smoi please open a new issue if you are having a problem.
