### ISSUE TITLE
How to keep rapns daemon working on heroku?

### ISSUE THREAD

**Issue by gcerquant** [ileitch/rapns#27]
I used this gem - thank you for the nice work! -, and deployed an app to heroku .
My environnement: Rails 3.1.3 - heroku cedar stack.

On my machine, after having launched the daemon with `bundle exec rapns development`, everything works fine, and I receive the push notifications.

**Trying to deploy it on heroku:
When I launch the daemon with the option --foreground, everything works fine, and I receive the push notification.
When I let the process fork into a daemon, it only lives for a few seconds.**

Command used on heroku:
# Works (but gets killed if I close my terminal window)
`heroku run bundle exec rapns production --foreground`

# Without the --foreground: Process doesn't live:
`heroku run bundle exec rapns production`

For example:
$ `heroku run bundle exec rapns production`

```
Running bundle exec rapns production attached to terminal... up, run.24
```

$ `heroku ps`

```
Process       State               Command
------------  ------------------  ------------------------------
run.24        complete for 6s     bundle exec rapns production
web.1         up for 49m          bundle exec rails server -p $PORT
```

Output of the logs at the same time:

```
2012-01-01T23:00:57+00:00 app[run.24]: Starting process with command `bundle exec rapns production`
2012-01-01T23:01:04+00:00 heroku[run.24]: State changed from up to complete
2012-01-01T23:01:05+00:00 heroku[run.24]: Process exited
```

I'm not sure where the issue is.
Do I need to scale my heroku config (tried to up the workers), or is there a bug with rapns when forking into a daemon?

**Comment by gcerquant** [comment]
Using the fact that the daemon does not live, I have found a hacky workaround:
After creating and saving the notification, I launch the daemon (without the --foreground flag) with system:

```
# ...
notification.save!
system("bundle exec rapns production") # On heroku, this process does its delivery job, but does not survive
```

It does not seem like a clean way to do this (especially due to the fact that we loose the fact that the daemon stays connected to Apple servers).
I would really appreciate if someone can chime in on this issue.

**Comment by ileitch** [comment]
I believe the correct solution is to add the following to your `Procfile`:

`rapns: bundle exec rapns $RACK_ENV -f`

**Comment by gcerquant** [comment]
Thank you for the reply.
I didn't know about `Procfile`. Thank you for the mention. More details for curious readers at: 
http://devcenter.heroku.com/articles/procfile

I have since switch to rapns to gain support of multiple applications, so I won't be able to further report on this issue.
Hopefully, this thread might help someone who will test this, and he will be able to comment

**Comment by EpicDraws** [comment]
I _love_ rapns and it has really helped speed development time, but running it on Heroku Bamboo runs into the same issue as above. Using the Procfile would be great, but its not supported in Bamboo. I suppose its a "legacy" app. but its only 9 months old and is in heavy use in production. To upgrade to Cedar is simply too large of a task for something so minor. 

Is there any way to keep this alive? I pay for several worker and web roles, so there must be a way?

**Comment by ileitch** [comment]
I've opened issue #33 as a base to talk about what improvement we can make. I'm afraid I wont have time to look at this myself until after the 22nd. If you do discover anything please comment in #33. Cheers.
