### ISSUE TITLE
Can't push messages containing colons

### ISSUE THREAD

**Issue by fredriproad** [ileitch/rapns#31]
This is a bug in RAPNS 1.0.2.

Messages are actually delivered, and they arrive at the device, but they only make a sound/vibrate -- they don't appear on screen,  display any text, appear in the notification center, or launch the app when unlocked.

This only happens when the message contains colons. Strip out the colons and everything is golden.

**Comment by ileitch** [comment]
I'm unable to reproduce this. Can you give me an example of your `alert`? Also what iOS version?

**Comment by fredriproad** [comment]
iOS 5.0.1 running on an iPhone 4s; I've gotten reports of issues on other devices too.

Here's some code:

First, here it works great:

``` ruby
n = Rapns::Notification.new
n.device_token = hex_token
n.alert = "test without colons"
n.save
```

Here, it breaks:

``` ruby
n = Rapns::Notification.new
n.device_token = hex_token
n.alert = "test with: one colon"
n.save
```

Yet here, it's fine!

``` ruby
n = Rapns::Notification.new
n.device_token = hex_token
n.alert = "test with :two: colons"
n.save
```

A notification is logged as having been sent successfully in both cases, and in both cases, the device does actually receive a notification of some sort, but when there are colons, it's like a ghost alert -- it makes a sound and vibrates, but there is no indicator of a notification anywhere, even in the notification center.

Note that this started happening this week when I switched from an old version of RAPNS (0.2.3) because of an issue with duplicate notifications going out. Apart from that issue, everything was working perfectly until the change. After changing it, I ran some tests and got the notifications, but then I started getting complaints that notifications weren't going through. I hadn't changed the code at all, and I had tested it myself, so I was puzzled as to why it was failing. After some debugging, I found that having a colon in the string made the difference -- no colons, ok, 2 colons, ok, but one colon, and this happens.

**Comment by fredriproad** [comment]
Ok, it looks like what's happening is that it's misinterpreting a string with a single colon as a JSON key/value pair.

``` ruby
    def alert
      string_or_json = read_attribute(:alert)
      ActiveSupport::JSON.decode(string_or_json) rescue string_or_json
    end
```

If you take `ActiveSupport::JSON.decode(string_or_json)` and feed it `"one:colon"` you get back `{"one"=>"colon"}`.

**Comment by ileitch** [comment]
Thanks for getting to the bottom of this. I'll push a fix as soon as I can.

**Comment by fredriproad** [comment]
Thanks Ian! :)

**Comment by fredriproad** [comment]
Another issue came up with the contents of alert messages -- a '#' will cause all subsequent characters in the alert to get cut off. Ex., `"Hello! This is day #100!"` becomes `"Hello! This is day "`

This turned a minor annoyance into a critical issue due to the kinds of notifications that I have to send out, so I fixed it locally and posted the fix to my fork.

The issue was caused here:

``` ruby
    def alert=(alert)
      if alert.is_a?(Hash)
        write_attribute(:alert, ActiveSupport::JSON.encode(alert))
      else
        write_attribute(:alert, alert)
      end
    end

    def alert
      string_or_json = read_attribute(:alert)
      ActiveSupport::JSON.decode(string_or_json) rescue string_or_json
    end
```

The line `if alert.is_a?(Hash)` in the setter method was correctly determining whether a given input was a hash and encoding it to JSON accordingly, but the line `ActiveSupport::JSON.decode(string_or_json) rescue string_or_json` in the getter was decoding strings that weren't originally hashes encoded as JSON.

I just added a flag to keep track of whether the input was originally encoded as JSON or not, and then only had it decode the string if so:

``` ruby
    @alert_is_json
    def alert=(alert)
      if alert.is_a?(Hash)
        write_attribute(:alert, ActiveSupport::JSON.encode(alert))
        @alert_is_json = true
      else
        write_attribute(:alert, alert)
        @alert_is_json = false
      end
    end

    def alert
      string_or_json = read_attribute(:alert)
      if @alert_is_json
        ActiveSupport::JSON.decode(string_or_json) rescue string_or_json
      else
        string_or_json
      end
    end
```

That fixed the issue with single colons, hash marks, and probably other characters in the alert. I hope it helps.

**Comment by ileitch** [comment]
Sorry you've had such trouble with this bug.

I don't see how your fix could have worked. Setting the flag in your Rails process would have no affect on the rapns process. I've pushed a fix to master that fixes this by persisting the flag in the database.

I'll probably release 1.0.4 with this fix tomorrow.

Cheers

**Comment by fredriproad** [comment]
Great; thanks Ian.

You're quite right -- the code effectively disabled the JS encoding/decoding of the alert content, so it fixed the problem I was having, but it would have broken the other functionality.
