### ISSUE TITLE
Multiple apps and database backed certificates

### ISSUE THREAD

**Issue by kuon** [ileitch/rapns#40]
We need to be able to send notifications to third party apps.

We created an interface in which developers can upload a certificate for their app.

Basically we need to be able to provide a certificate when we create the notification.

Before I start hacking rapns I was wondering what you though.

**Comment by ileitch** [comment]
Yes I'd like to add this ability. My concerns are:
1. Keep rapns simple to setup for users with only a single app/certificate.
2. Make the upgrade process painless (I assume these changes will require changes to the rapns.yml layout).

Also, this may not be the case for your application. But I'd like to investigate decoupling rapns from Rails as part of this. Some users wanting this feature may have multiple Rails applications, but will require only a single rapns daemon. Having to deploy one of those Rails apps just to house rapns makes for a rather awkward deployment process. 

I'll investigate this further over the next couple of days.

**Comment by kuon** [comment]
I guess the easiest way for decoupling would be to provide a backend class to store the notifications, having perhaps a file based backend in addition to the activerecord backend. The backend class would implement something like `save(notification)` and `dequeue`. Then the notification object would become a simple `Object` subclass wrapping the notification info.

Anyway thanks for looking into this, if I can help, just let me know.

**Comment by ileitch** [comment]
I have just pushed multi-app support to master. Would you also give it a try?

To configure your apps you add a section to rapns.yml, e.g:

```
  app1:
    certificate: production.pem
    certificate_password:    
    connections: 3

  app2:
    certificate: production.pem
    certificate_password:    
    connections: 3
```

```
n = Rapns::Notification.new
n.app = "app1"
...
```

**Comment by kuon** [comment]
Would it be possible to specify the config at runtime? Our certificates live in the db.

**Comment by ileitch** [comment]
OK, I have now change master to read App configuration from the database.

```
app = Rapns::App.new
app.key = 'my_app'
app.environment = 'production'
app.certificate = File.read('production.pem')
```

Please give it a try. I'm also thinking it'd be nice to monitor Rapns::App and start/stop delivery handlers as needed.

**Comment by kuon** [comment]
Great.

I am working on another project for a few day, but I'll be back on the rails application very soon. I'll try that fully then. 

## 

Nicolas Goy
Programmer

Goyman.com SA
Versvey 57
1853 Yvorne
SWITZERLAND

Phone: +41 21 535 31 13
Mobile: +41 79 935 68 93

**Comment by EpicDraws** [comment]
What is the full format for specifying multiple apps in rapns.yml? I tried to simply add the app sections inline to no avail.

**Comment by ileitch** [comment]
I've changed that, apps are now added by creating an Rapns::App. See the readme.
Note that this functionality in only in mater currently, not a gem.

**Comment by ileitch** [comment]
This is now supported in 2.0.0.
