### ISSUE TITLE
rapns fails to start on Heroku with ActiveRecord 3.2.5 

### ISSUE THREAD

**Issue by tompesman** [ileitch/rapns#43]
Due to this commit in ActiveRecord rapns fails to start with ActiveRecord 3.2.4/3.2.5 on Heroku. 
rails/rails@8e315b0e0a551fcb09e73b2b704492923d4806f3

lib/rapns/patches.rb:

``` ruby
if ActiveRecord::Base.configurations[Rails.env]['adapter'] == 'postgresql'
```

It fails as there is no 'configurations' available: `lib/rapns/patches.rb:1:in '<top (required)>': undefined method '[]' for nil:NilClass (NoMethodError)`

I don't have a pull request right now, but I think you should also check for the `ENV['DATABASE_URL']`.

**Comment by ileitch** [comment]
Thanks, i'll get to this soon.
