### ISSUE TITLE
Support mixed-mode environments per app

### ISSUE THREAD

**Issue by EpicDraws** [ileitch/rapns#46]
With the multi-app solution, I'd like to run some of the apps in production environment, and some in development. Is this possible today? I tried setting the environment name on each Rapns::App and having the different sandbox and production server info in the rapns.yml.

**Comment by EpicDraws** [comment]
Note: This is as a result of #40. Thanks for multi-app support, and looking forward to single daemon, mixed-environment support!

**Comment by ileitch** [comment]
I've been pondering this, I think I'm going to get rid of `rapns.yml` altogether and have the `host` and `port` defined on `Rapns::App`. The `environment` attribute will set defaults for `host` and `port` to keep rapns easy to setup for new users.

All other config options will be set as command line flags.

I'm going to sleep on this, as it's quite a big change for existing users.

**Comment by EpicDraws** [comment]
Hey Ian, 

Thanks for taking a look, and thanks again for the great gem.

I think your approach sounds good, and would satisfy the requirements of a multi-app, cross-environment deployment like mine. 

In order to leave current users unaffected, can you have the command line option become optional? If given, it looks to the existing rapns.yml file. Once you have the new solution in place, what is the point of a command line environment flag?

Also, is there any quick hack or patch you know of in the mean time to unblock my dual-environment testing? Even if I launch a separate instance for each environment, it appears they compete for notifications which causes issues (as a production bound notification gets queued by the development instance). 

Thanks!

**Comment by ileitch** [comment]
I guess you could set the key on the notification to something like "my_app_development" and do the same on the App.

**Comment by EpicDraws** [comment]
Not sure I follow, could you elaborate?
On Jun 15, 2012 6:43 PM, "Ian Leitch" <
reply@reply.github.com>
wrote:

**Comment by ileitch** [comment]
I have just implemented a different approach. The environment is now automatically detected from the app certificate. Please give it a try.

**Comment by EpicDraws** [comment]
Thanks for the quick work, I was out of town. Will take a look tonight and provide feedback. Thanks again!

**Comment by EpicDraws** [comment]
It appears to work for my existing production app, but I get a [ERROR] Could not detect environment for app 'my_app'. for the development one. It has a development certificate set and the .environment is set to 'development'. 

Any ideas? I am still launching it from the command line with production.

**Comment by ileitch** [comment]
I actually removed the `environment` attribute, though I will have to add it back if the auto-detection isn't viable.

rapns is looking for the string 'Apple Development IOS Push Services' in your development certificate, which it appears it does not contain. Can you see anything similar in there?

**Comment by EpicDraws** [comment]
http://pastie.org/4112348

I changed some characters so its no longer valid, but the full structure is still there. That is my development one.

**Comment by EpicDraws** [comment]
Strangely, I just looked at the certificate for my (older by a few months) project in production, and it has the properties you mention:

Bag Attributes
    friendlyName: Apple Production IOS Push Services: com.blah.MyApp
    localKeyID: B5 8E E3 40 E3 10 09 AB 68 38 64 FF A9 6A 23 55 D8 82 26 
subject=/UID=com.blah.MyApp/CN=Apple Production IOS Push Services: com.blah.MyApp/C=US
issuer=/C=US/O=Apple Inc./OU=Apple Worldwide Developer Relations/CN=Apple Worldwide Developer Relations Certification Authority
-----BEGIN CERTIFICATE-----

I'll regenerate the new app one to make sure its not an issue on my end.

**Comment by EpicDraws** [comment]
Sorry, one more note, the production version for the new app does not have those similar properties, it looks nearly identical to the development one. These were generated a few days ago in iTunes Connect.

**Comment by EpicDraws** [comment]
I was able to verify at least the development certificate works by using the older version of rapns in development mode. Pushes were successfully received. Did Apple change the format or am I doing something wrong? I set the environment variable on the Rapns::App, so perhaps when there is a failure to auto-detect it can fall back to that?

**Comment by ileitch** [comment]
I've just committed a revet of the auto-detect. Auto-detect would have been nice, though it does depend on Apple adding those strings to those certs, and then whatever tool people use to export the certificates and convert them to .pem to retain them also.

I'll release 2.0.0 tomorrow or the day after unless you find any further issues. Thanks for giving it a try!

**Comment by EpicDraws** [comment]
Works perfectly and as expected, thanks! Closing this issue as this resolves my needs. Thanks for the quick turnaround and discussion.
