### ISSUE TITLE
Having upgraded to 2.0.0, Rapns daemon seems not to work properly on production

### ISSUE THREAD

**Issue by hlandao** [ileitch/rapns#50]
I've been using this great gem for a while locally in development environment and everything worked well. After upgrading to 2.0.0, running it remotely on production environment does not work properly.

I successfully create new notification with :
    n = Rapns::Notification.new
    n.app = "testapp"
    n.device_token = "HEX"
    n.alert = "Test notification!!"
    n.badge = 1
    n.sound = "1.aiff"
    n.expiry = 1.day.to_i
    n.deliver_after = 1.hour.from_now
    n.save!

However, running Rapns daemon in foreground mode gives no indication that anything had happend and the rapns.log file is empty.

Am I doing anything wrong or is there an issue with the new version ?

Thanks anyhow,
Hadar.

**Comment by ileitch** [comment]
Are you using ruby 1.8?

**Comment by ileitch** [comment]
I have pushed a fix to master for 1.8, can you give it a try?

`gem 'rapns', :github => 'ileitch/rapns'`

**Comment by hlandao** [comment]
Hi, Thanks for fast response.
I'm using ruby 1.9.2

I actually having a problem installing gems from git so couldn't even try your fix (though im not on  1.8 so it does not matter much)

Thanks,
Hadar.

**Comment by ileitch** [comment]
Oh OK. Have you checked that `Rapns::App#key` matches `Rapns::Notification#app`?

2.0.0 is very different in terms of configuration, take a look at the README.

**Comment by hlandao** [comment]
yeah, i used the same app key, it seems that remotely on CENTOS - the daemon does not work ? any ideas ?

**Comment by hlandao** [comment]
BTW - how can verify the status of the daemon ?

**Comment by ileitch** [comment]
1. Check production.log to verify the daemon is performing queries.
2. Start the daemon in foreground mode `--foreground`, then send it the USR1 signal and paste here the output. `kill -USR1 <pid>`

**Comment by hlandao** [comment]
I have found no evidence for RAPNS activity in the production log, while I do recognize it's activity in the development log.

However, I got the following error now after running 'bundle exec rapns production -f' (for the first time) :
[root@centos01 faceforplace]# bundle exec rapns production -f
[2012-07-07 22:32:01] [ERROR] Errno::ETIMEDOUT, Connection timed out - connect(2)
/usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/connection.rb:100:in `initialize'
/usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/connection.rb:100:in`new'
/usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/connection.rb:100:in `connect_socket'
/usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/connection.rb:23:in`connect'
/usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/feedback_receiver.rb:37:in `check_for_feedback'
/usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/feedback_receiver.rb:21:in`block (2 levels) in start'
/usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/feedback_receiver.rb:19:in `loop'
/usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/feedback_receiver.rb:19:in`block in start'
/usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/connection.rb:100:in `initialize': Connection timed out - connect(2) (Errno::ETIMEDOUT)
    from /usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/connection.rb:100:in`new'
    from /usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/connection.rb:100:in `connect_socket'
    from /usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/connection.rb:23:in`connect'
    from /usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/delivery_handler.rb:29:in `start'
    from /usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/app_runner.rb:113:in`start_handler'
    from /usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/app_runner.rb:79:in `block in start'
    from /usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/app_runner.rb:79:in`times'
    from /usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/app_runner.rb:79:in `start'
    from /usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/app_runner.rb:45:in`block in sync'
    from /usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/app_runner.rb:37:in `each'
    from /usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon/app_runner.rb:37:in`sync'
    from /usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/lib/rapns/daemon.rb:38:in `start'
    from /usr/local/lib/ruby/gems/1.9.1/gems/rapns-2.0.0/bin/rapns:46:in`<top (required)>'
    from /usr/local/lib/ruby/gems/1.9.1/bin/rapns:23:in `load'
    from /usr/local/lib/ruby/gems/1.9.1/bin/rapns:23:in`<main>'

**Comment by ileitch** [comment]
Do you get the timeout errors each time you start rapns?

What's your `Rapns::App#environment` set to?

**Comment by hlandao** [comment]
In the current configuration it is set to 'development' even though it is basically a rails production env..because my iPhone client is still in dev stage.

does it matter ? isn't it attempting to connect to the sandbox server whenever the Rapns::App#environment is set to 'development' ?

**Comment by ileitch** [comment]
Yes that is correct. I have no idea why you are unable to connect to the sandbox, I am able to do so. It appears not to be an issue with rapns. Are you able to connect to the sandbox using other tools?

`$ telnet gateway.sandbox.push.apple.com 2195
Trying 17.149.34.65...
Connected to gateway.sandbox.push-apple.com.akadns.net.
Escape character is '^]'`

**Comment by hlandao** [comment]
Ohh seem that's the problem.
I actually cannot confirm it because im now unable to open the relevant ports but the telenet gives timeout as well.

anyway thanks,
I guess we can actually close this issue for now.

Thanks a lot,
Great job, get gem,
Hadar.

**Comment by ileitch** [comment]
OK, thanks. Good luck finding a solution.
