### ISSUE TITLE
ActiveRecord::ConnectionNotEstablished when installing rapns

### ISSUE THREAD

**Issue by trnc-ck** [ileitch/rapns#53]
when adding the rapns gem in gemfile, execute bundle install and trying to rails g rapns, i get the following error:

/Users/foo/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:404:in `retrieve_connection': ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)

using rails 3.2.6 and ruby 1.9.3

when remove rapns from gemfile it works again. any advice?

**Comment by complex** [comment]
I get the same thing with Rails 3.1.6 and Ruby 1.9.3. It started for me when I installed Mountain Lion — in Lion, I had no problem.

**Comment by trnc-ck** [comment]
did mountain lion update as well today! maybe a rails issue?

**Comment by complex** [comment]
The issue seems to be specific to rapns 2.0.2. I reverted to 2.0.1 and it works fine.

**Comment by ileitch** [comment]
Yeah sorry, I messed up 2.0.2. New release coming in a new minutes.

**Comment by trnc-ck** [comment]
thanks ileitch!

**Comment by ileitch** [comment]
Fixed in 2.0.3.

**Comment by complex** [comment]
Thanks for the quick fix!
