### ISSUE TITLE
device_token validation fails?

### ISSUE THREAD

**Issue by trnc-ck** [ileitch/rapns#54]
i try to send a notification to "02b8ed402230776c6a26f1d189457b9f4c188d8a", but the validation is telling 

Validation failed: Device token is invalid

what is rapns validating? type and length should be alright? is it a bug?

thanks!

**Comment by ileitch** [comment]
Device tokens are 64 bytes long. Are you sure that's the device token and not the device ID?

**Comment by trnc-ck** [comment]
you are right, sry ;) remove pls!
