### ISSUE TITLE
Starting the rapns daemon when no app exists

### ISSUE THREAD

**Issue by dei79** [ileitch/rapns#55]
I tried to start the rapns deaemon when no application exists. This breaks with the following error:

!!!! RAPNS NOT STARTED !!!!

You must create an Rapns::App.
See https://github.com/ileitch/rapns for instructions.

I plan to use the HUP hot update feature to notify rapns that a new application comes in. When I deploy my application to a new server and I bring all daemons app and running (based on god) naturally no application exists. 

Any options?

**Comment by ileitch** [comment]
Not currently, but I'm happy to turn the error into a warning.

**Comment by dei79** [comment]
So if this mean the daemon would run and I can use the HUP message to register a new app then it would be great. Otherwise I need to check out your code more in deep :-)

**Comment by ileitch** [comment]
Fixed in 2.0.4
