### ISSUE TITLE
How to kill the Daemon

### ISSUE THREAD

**Issue by robert2d** [ileitch/rapns#56]
I have no idea how to kill the daemon on our staging sever which appears to be running multiple daemons aswell. 

I cannot find the pid file anywhere nor can I see it using `ps aux` 

Can somebody please let me know how to KILL it

**Comment by ileitch** [comment]
What is the symptom you are seeing that makes you suspect there are multiple daemons running?

`ps aux | grep rapns` gives you nothing? I'm not sure how that can be...

**Comment by robert2d** [comment]
Hey thanks for the response,

I am running rapns on our staging server and have found it printing a massive amount of queries to the logs. I have successfully killed the daemon now so I will give it another shot. 

But to be honest I think there may be other things happening. When you run `bundle exec rapns staging' will it start a new daemon even when one is has already been started? or will it replace the current one? 

Apart from the slight panic attack it gave me. I am finding the Rapns gem to be a real "Gem", its really efficient.

Great work. Thanks Dave.

**Comment by ileitch** [comment]
Yes, running it twice will result in multiple daemons.

As for the many queries in the logs, that's normal. rapns polls the database for new notifications. You can reduce the frequency to suit your needs, run rapns --help for options.

**Comment by robert2d** [comment]
Okay good to know, sorry to bother you. Next time i wont start a new one without stoping the old one.
