### ISSUE TITLE
UTF-8 symbols in alert

### ISSUE THREAD

**Issue by alxgsv** [ileitch/rapns#6]
I am using utf-8 symbols in alert messages, but instead of 

`Аттикус Финч`

I am receiving

`\xD0\x90\xD1\x82\xD1\x82\xD0\xB8\xD0\xBA\xD1\x83\xD1\x81 \xD0\xA4\xD0\xB8\xD0\xBD\xD1\x87`

I use ruby 1.8.7

How can I work-around it?

**Comment by ileitch** [comment]
Hi, I've not tested with UTF-8 yet, i'll have a look into it soon.

**Comment by alxgsv** [comment]
Sorry, Ian. That was my fault — I used mysql adapter instead of mysql2 in rails 3.1 + ruby 1.9.2 setup

utf8 in alert is sending properly
