### ISSUE TITLE
god configuration

### ISSUE THREAD

**Issue by dei79** [ileitch/rapns#64]
I played a bit with your sample god configuration. I also read that it's better to let god do the daemonizing. There are anything against the following change of the god configuration

God.watch do |w|
  w.name = 'rapns'

  w.start = "cd #{rails_root} && bundle exec rapns #{rails_env} -f"

  w.uid = 'deploy'
  w.gid = 'deploy'

  w.keepalive
end

**Comment by dei79** [comment]
At least the following needs to be changed when we want to use the sample god config

w.start = "cd #{rails_root} && bundle exec rapns #{rails_env} -p #{rails_shared}/pids/rapns.pid"

Understood the issue with the -f, not the best idea without changing the daemon.rb implementation

**Comment by ileitch** [comment]
Can you please show me where it says not forking is better?

**Comment by dei79** [comment]
Whithout the -p option I got the following log:

I [2012-08-14 09:50:30]  INFO: rapns moved 'init' to 'start'
I [2012-08-14 09:50:30]  INFO: rapns [ok] process is not running (ProcessRunning)
I [2012-08-14 09:50:35]  INFO: rapns [ok] process is not running (ProcessRunning)

And god tries to start a new instance of rapns until the available memory is empty :-(

**Comment by dei79** [comment]
What Rapns 2.x I got my god config running when I'm using the -p parameter. When I start stop via god very fast one process stays in the system. This is not really an issue in production environments I think.

**Comment by ileitch** [comment]
I'll look into this soon, thanks.

**Comment by dei79** [comment]
ok I migrated to 3.1 and know everything works fine
