### ISSUE TITLE
Heroku logging issues

### ISSUE THREAD

**Issue by masterkain** [ileitch/rapns#65]
Hello,
I'm running on Heroku in staging environment, I get this error on startup, preventing me from using rapns:

```
/app/vendor/bundle/ruby/1.9.1/gems/rapns-2.0.4/lib/rapns/daemon/logger.rb:6:in `initialize': No such file or directory - /app/log/rapns.log (Errno::ENOENT)
```

Procfile:

```
apn: bundle exec rapns $RACK_ENV -f -n
```

Am I the only one with this issue? Rails 3.2, Cedar stack.

**Comment by Mooed** [comment]
Have you found a workaround or solution for this?

**Comment by Mooed** [comment]
So removing this line from application.rb worked for me:
config.logger = Logger.new(STDOUT)

**Comment by ileitch** [comment]
I'll look into this in the next few days.
