### ISSUE TITLE
App#environment validation is too strict

### ISSUE THREAD

**Issue by jcoleman** [ileitch/rapns#66]
Rapns makes the assumption that the only environments possible in Rails are `development` and `production`. Most of the projects I work on currently have `staging` environments as separate from `production`.

I see two possible solutions: find a way to interrogate Rails to find all possible environments or just remove the validation as the worst case scenario with a typo'd environment is that the notifications aren't sent. I haven't found any way yet to determine the possible environments in a Rails app, so I think think it makes sense to just remove the validation.

Thoughts?

Edit: I see now why that's important; Rapns needs to know how to map the environment to the correct Apple gateway. Perhaps it could default everything except production to the sandbox and accept configuration for anything else?

**Comment by ileitch** [comment]
App#environment is the APN environment, which is only ever development or production. You specify your Rails environment as the first argument to rapns on the command line.

I should make that clear in the readme.

**Comment by jcoleman** [comment]
That all makes sense. I'm closing this issue then.
