### ISSUE TITLE
rapns on Windows Server 2008 R2

### ISSUE THREAD

**Issue by zmajstor** [ileitch/rapns#71]
Any idea how to start rapns deamon on Windows Server 2008 R2 with installed Ruby 1.9.3p0 and all needed Rails gems?
Here is error stack after command prompt command: `bundle exec rapns production`

```
c:/Ruby19/lib/ruby/gems/1.9.1/gems/rapns-2.0.4/lib/rapns/daemon.rb:72:in `trap': unsupported signal SIGHUP (ArgumentError)
      from c:/Ruby19/lib/ruby/gems/1.9.1/gems/rapns-2.0.4/lib/rapns/daemon.rb:72:in `setup_signal_hooks'
      from c:/Ruby19/lib/ruby/gems/1.9.1/gems/rapns-2.0.4/lib/rapns/daemon.rb:30:in `start'
      from c:/Ruby19/lib/ruby/gems/1.9.1/gems/rapns-2.0.4/bin/rapns:46:in `<top (required)>'
      from c:/Ruby19/bin/rapns:19:in `load'
      from c:/Ruby19/bin/rapns:19:in `<main>'
```

**Comment by ileitch** [comment]
Thanks for reporting. I don't have an answer for you right now, I will have to look into how Windows does signal handling.

**Comment by zmajstor** [comment]
As quick fix, maybe introduction of new config option `signal_hooks` could help?
e.g. line 72 of lib/rapns/daemon.rb could be something like this:

```
config.signal_hooks ? setup_signal_hooks : Rapns::Daemon.logger.info('starting without signal_hooks')
```

**Comment by ileitch** [comment]
Can you show me the output of `Signal.list`?

**Comment by zmajstor** [comment]
this is the output of `Signal.list`

```
{"EXIT"=>0, "INT"=>2, "ILL"=>4, "ABRT"=>22, "FPE"=>8, "KILL"=>9, "SEGV"=>11, "TERM"=>15}
```

more info about Signals on Windows:
http://msdn.microsoft.com/en-us/library/xdkz3x12(v=vs.71).aspx
http://msdn.microsoft.com/en-us/library/ms811896#ucmgch09_topic3

**Comment by ileitch** [comment]
I have no way to test a fix for this. Please reopen if there's still interest.
