### ISSUE TITLE
Validate Notifications to not exceed allowable length for APS protocol

### ISSUE THREAD

**Issue by mattconnolly** [ileitch/rapns#73]
Add a validator to the Rapns::Notification model to prevent a payload of more than 256 bytes as per protocol:

https://developer.apple.com/library/ios/#documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/ApplePushService/ApplePushService.html#//apple_ref/doc/uid/TP40008194-CH100-SW9

When notifications are to be delivered later, the failure will not be known until a later time, which may be frustrating for the user sending the notification to not know if it will be sent or not. This failure condition can be prevented with a validator.

**Comment by mattconnolly** [comment]
It says "No one is assigned", and i can't see a way to assign myself to this issue. I'll get this one done this week...

**Comment by ileitch** [comment]
There is already validation for this. Can you show me some code to reproduce the error?

**Comment by mattconnolly** [comment]
Snap. It does too. My controller, didn't check for the error. Haste makes waste. :/
