### ISSUE TITLE
Error sending notification w/o any attributes

### ISSUE THREAD

**Issue by intouchmvc** [ileitch/rapns#74]
ArgumentError: wrong number of arguments (2 for 1)
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/multi_json-1.0.3/lib/multi_json.rb:71:in `encode'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/rapns-2.0.4/lib/rapns/notification.rb:104:in`multi_json_dump'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/rapns-2.0.4/lib/rapns/notification.rb:77:in `payload'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/rapns-2.0.4/lib/rapns/notification.rb:81:in`payload_size'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/rapns-2.0.4/lib/rapns/binary_notification_validator.rb:5:in `validate'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:302:in`_callback_before_13'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:449:in `_run_validate_callbacks'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:81:in`run_callbacks'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activemodel-3.1.0/lib/active_model/validations.rb:212:in `run_validations!'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activemodel-3.1.0/lib/active_model/validations/callbacks.rb:53:in`block in run_validations!'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:390:in `_run_validation_callbacks'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:81:in`run_callbacks'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activemodel-3.1.0/lib/active_model/validations/callbacks.rb:53:in `run_validations!'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activemodel-3.1.0/lib/active_model/validations.rb:179:in`valid?'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/validations.rb:69:in `valid?'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/validations.rb:77:in`perform_validations'
... 4 levels...
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/transactions.rb:208:in`transaction'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/transactions.rb:293:in `with_transaction_returning_status'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/transactions.rb:241:in`block in save'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/transactions.rb:252:in `rollback_active_record_state!'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/transactions.rb:240:in`save'
    from /home/deploy/releases/20121004172140/app/models/person.rb:310:in `block in send_push_notification'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/associations/collection_proxy.rb:91:in`each'
    from /home/deploy/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/associations/collection_proxy.rb:91:in `method_missing'
    from /home/deploy/releases/20121004172140/app/models/person.rb:289:in`send_push_notification'

I'm hoping this is just a missing gem requirement.

**Comment by ileitch** [comment]
This looks like a MultiJson version incompatibility. What version do you have?
