### ISSUE TITLE
Rapns and ODBC connection to SQL Azure problem

### ISSUE THREAD

**Issue by stibra** [ileitch/rapns#80]
I have problem with push when using SQL Azure database using ruby-odbc driver. Device token which is normaly 64 characters, Rapns sends only 63 characters and two NULLs (visible in the rapns log file). Device token is 64 characters long in the database.
There is no problem when using local SQL 2008 R2 Server and tiny-tds, but I can not use tiny-tds to connect to Azure.

Any idea what might be the problem?

Thanks,

Ratko

**Comment by ileitch** [comment]
I do not know, are you running rapns on Windows?

**Comment by stibra** [comment]
Yes, I am running rapns on Windows! It was problem with ODBC driver version, it should work now!
