### ISSUE TITLE
Use rapns with cron/scheduler

### ISSUE THREAD

**Issue by jamesxyz** [ileitch/rapns#81]
I want to use rapns with Heroku, but I don't have that much traffic that makes it worth while to use a dedicated worker.

How can I use this with e.g. Heroku's Scheduler, is it possible to send notifications and process feedback with one time commands (rake) instead of running a permanent daemon?

**Comment by ileitch** [comment]
There isn't a way to do this currently, though adding such a feature should be pretty simple. I am currently working on version 3.0 which is in beta, I will add this feature. I hope to release 3.0 in a couple of weeks.

**Comment by ileitch** [comment]
This is now implemented in master and will be part of 3.1.

**Comment by ileitch** [comment]
To use it: `Rapns.push`

**Comment by koloritcm** [comment]
Nice! How do you process feedback and remove inactive device tokens in the same one-time way without the daemon?

**Comment by koloritcm** [comment]
@ileitch How do you download and process feedback as a one-time operation from a scheduler?

**Comment by ileitch** [comment]
I'll add a new API for this, probably `Rapns.feedback`. I've opened #100 for this feature.

**Comment by koloritcm** [comment]
Thanks!

**Comment by ileitch** [comment]
Good news, no new code needed for this (I'm sorry for not realizing this was the case sooner). `Rapns.push` is almost identical to starting from the command line, so it actually also starts the `FeedbackReceiver`.

`Rapns.push` will not return until all feedback has been received (if there is any). Check your database for feedback records.

You can also use the [Reflection API](https://github.com/ileitch/rapns/wiki/Reflection-API) to implement custom feedback handling.
