### ISSUE TITLE
not always receiving the message

### ISSUE THREAD

**Issue by shaokun** [ileitch/rapns#82]
Hi, I am testing with one device in development. It works pretty well.
But I am not always receiving the message in my iPhone even the RAPNS said that it's delivered without any errors, also no error in Feedback service.
Is this normal?

Also, I noticed that RAPNS use multiple connections (threads) to speed up when delivering tons of notifications. I am wondering if I could use more than one physical servers, with one RAPNS on one server to improve the performance much more? Will Apple not like that?

**Comment by ileitch** [comment]
I have also seen messages not being received, this is expected as Apple do not guarantee that messages will be delivered. The situation may be better in the production environment. What % do you see being lost?

Rapns doesn't support being run on multiple servers, you'll end up duplicate notifications being sent if you do. How many notifications are you expecting to deliver? Rapns should be able to handle very high throughput. You can also use `--no-error-checks` for increased throughput.

**Comment by shaokun** [comment]
Thanks for replying. `--no-error-checks` should probably help.
I just tried 10 messages, got 8, 2 loss. So maybe 10% more or less loss in development.

I actually forked the gem and added a server field to the notification. So that I could assign the notification to different servers. I am expecting to deliver 0.5 million messages.

**Comment by ileitch** [comment]
Are you able to try using the production environment?

0.5m per day?

Please open a pull request with the multi-server changes, I'm happy to work on that with you for 3.0 (master).

**Comment by shaokun** [comment]
Not able to do it in production yet. Will post here when I get the data :).

I am developing the push feature for an existing app, and it's installed on about 0.5m iPhones.
So whenever there is an notification, it might be pushed to all the clients. There is going to be some filter to select a subset of clients too. But I am expecting at most 0.5m notifications once.

It would be awesome to contribute to this nice gem.
Let me rethink about my hacks and see if I could come out something better.

**Comment by ileitch** [comment]
Please reopen if you have more info.
