### ISSUE TITLE
Send to token-group?

### ISSUE THREAD

**Issue by trnc-ck** [ileitch/rapns#88]
hi,

what's the recommended way to send notifications to e.g. 1000 tokens? making a new notification object for every token is a bit of overkill?

thanks!

**Comment by ileitch** [comment]
The APNs does not support sending the same notification to many devices, nor does Rapns provide a way to create a bulk notification.

I am planning on adding support for swappable storage backends in 3.1 with Redis being the first alternative to ActiveRecord.
