### ISSUE TITLE
Getting 'wrong number of arguments' when calling Notifications.new

### ISSUE THREAD

**Issue by nicw** [ileitch/rapns#89]
Following the 3.0 instructions verbatim, I've setup an App, and am trying to create a test notification. But ActiveRecord is throwing an error on notification.rb.
Rails 3.0.9, Ruby 1.9.2

`1.9.2-p320 :008 > n = Rapns::Apns::Notification.new
ArgumentError: wrong number of arguments (2 for 1)
    from /Users/nicwerner/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.0.9/lib/active_record/base.rb:1399:in`initialize'
    from /Users/nicwerner/.rvm/gems/ruby-1.9.2-p320/gems/rapns-3.0.0.rc.1/lib/rapns/notification.rb:33:in `initialize'
    from (irb):8:in`new'
    from (irb):8
    from /Users/nicwerner/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.0.9/lib/rails/commands/console.rb:44:in `start'
    from /Users/nicwerner/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.0.9/lib/rails/commands/console.rb:8:in`start'
    from /Users/nicwerner/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.0.9/lib/rails/commands.rb:23:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'
`

**Comment by ileitch** [comment]
Fixed in 3.0.1, thanks for reporting!

**Comment by nicw** [comment]
Thanks for the quick turnaround!
